variables:
  SAST_IMAGE_SUFFIX: '-fips'

stages:
  - build
  - test
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml

build-job:
  stage: build
  script: 
    - echo "Hello, $GITLAB_USER_LOGIN!"
  
testjob1:
  stage: test
  script: 
    - ./tests/run_tests.sh


deploy-prod:
  stage: deploy
  script: 
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
