name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    # SECURITY WARNING: This workflow uses `pull_request_target`, which runs with secrets and write permissions
    # for pull requests from forks. This is necessary for the `actions/first-interaction` action to post a
    # comment. DO NOT add any steps that check out or run code from the pull request (e.g., `actions/checkout`
    # or any `run` scripts). Doing so would create a critical security vulnerability.
    - uses: actions/first-interaction@fb2402657b4a28582200150d0a145671d0e50597 # Pin to v1 commit
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
